# Generated by Django 4.2.1 on 2023-06-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('producty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producty')),
            ],
        ),
    ]
