# Generated by Django 4.2.1 on 2023-07-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review_rate_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='producty',
        ),
        migrations.AddField(
            model_name='producty',
            name='review',
            field=models.ManyToManyField(blank=True, to='product.review'),
        ),
        migrations.AlterField(
            model_name='producty',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
