# Generated by Django 4.2.1 on 2023-07-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_review_producty_producty_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producty',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
        migrations.AddField(
            model_name='review',
            name='producty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='product.producty'),
        ),
        migrations.AlterField(
            model_name='producty',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_producty', to='product.category'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '* '), (2, '* * '), (3, '* * * '), (4, '* * * * '), (5, '* * * * * ')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
    ]
