# Generated by Django 4.2.1 on 2023-07-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_producty_review_remove_review_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producty',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
